### ISSUE TITLE
Back wall missing on Alpha 0.52 C1a1 decompile

### ISSUE THREAD

**Issue by Droooga** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#14]
Title says it all. 
![kuva](https://user-images.githubusercontent.com/85588460/201383583-5ff46e76-63e8-4b8f-945e-109bc1800c85.png)
happens on both brush optimizing methods

**Comment by SamVanheer** [comment]
That's to be expected, decompilers for Half-Life 1 will never be able to produce 100% accurate results.

**Comment by UnrealKaraulov** [comment]
Possible need create new decompiler, instead of use old versions that create bad results ?

@SamVanheer I can add decompiler to bspguy ?

I added .obj decompiler : https://github.com/UnrealKaraulov/newbspguy/blob/360929dde456cb5e3c103e2fb885f25d4942684c/src/bsp/Bsp.cpp#L4402 

But don't know how to make .map decompiler :)

**Comment by SamVanheer** [comment]
There isn't enough data in HL1 BSP files to accurately recreate maps.

**Comment by UnrealKaraulov** [comment]
> There isn't enough data in HL1 BSP files to accurately recreate maps.

@SamVanheer but for example Sledge can import obj, possible to use this to rebuild needed data for do better export?

**Comment by SamVanheer** [comment]
It looks like Sledge attempts to rebuild brushes when it imports obj files that lack complete brushes (see https://github.com/LogicAndTrick/sledge/blob/master/Sledge.BspEditor/Providers/ObjBspSourceProvider.cs) but exporting as obj is something i don't want to add here since it's not strictly decompilation and because this project is GPL-licensed.

I want to keep the amount of GPL'd code to a minimum in my HL projects so an obj exporter would be a separate project. I have had a request for it already though, so i'll try to make one at one point.
